### ISSUE TITLE
Token.txt

### ISSUE THREAD

**Issue by Robin18m** [whoisbaby/TwitchFollowers#1]
Hey man!

I need to put tokens in the token.txt, but how can i get the right tokens? 

  error: 'Unauthorized',
  status: 401,
  message: 'The "Authorization" token is invalid.'

**Comment by whoisbaby** [comment]
You can buy tokens from sellers is like 1$ / 1k tokens

**Comment by RobinKlok16** [comment]
> You can buy tokens from sellers is like 1$ / 1k tokens

Can u send invite to the sellers? XD

**Comment by whoisbaby** [comment]
i fine one and i send you 👍

**Comment by whoisbaby** [comment]
i edited message up

**Comment by whoisbaby** [comment]
@RobinKlok16

**Comment by idkwhattoputhere121** [comment]
Buy what token? Don't you need just a bot token?

**Comment by RobinKlok16** [comment]
> Buy what token? Don't you need just a bot token?

Yes u also need a bot token. And you need twitch tokens.

**Comment by idkwhattoputhere121** [comment]
What kind of twitch tokens?

**Comment by oriolvinals** [comment]
need a bot seller

**Comment by Tomy-G** [comment]
> You can buy tokens from sellers is like 1$ / 1k tokens
> 
> Here is a seller: https://discord.gg/nmDT9mCKps

The Discord invitation expired, please could you tell me where can i find any seller? I've searched but can't find anything.

**Comment by WANTED10** [comment]
Is it possible to login in twitch using a token?

**Comment by joeyc00l** [comment]
i sell tokens dm me on discord GeneralOG#8242

**Comment by burb7898** [comment]
I have 3.6k tokens if you need
