### ISSUE TITLE
Issue With Adding Tokens

### ISSUE THREAD

**Issue by Shadow-Myxtics** [whoisbaby/TwitchFollowers#15]
I will add over 100 tokens but it will only load 1 token... Can somebody help me

**Comment by ChikoShidori** [comment]
[Index.js line 18](https://github.com/whoisbaby/TwitchFollowers/blob/main/index.js#L18), remove the string of the split and paste this regex `/\s+/`

I don't know why you need the filter there, but if you want to, put the filter

```js
tokens = tokens.split(/\s+/))
```

**Comment by whoisbaby** [comment]
> [Index.js line 18](https://github.com/whoisbaby/TwitchFollowers/blob/main/index.js#L18), remove the string of the split and paste this regex `/\s+/`
> 
> I don't know why you need the filter there, but if you want to, put the filter
> 
> ```js
> tokens = tokens.split(/\s+/)
> ```

make a pull request with this and i can merge if you want

**Comment by chikof** [comment]
> > [Index.js line 18](https://github.com/whoisbaby/TwitchFollowers/blob/main/index.js#L18), remove the string of the split and paste this regex `/\s+/`
> > I don't know why you need the filter there, but if you want to, put the filter
> > ```js
> > tokens = tokens.split(/\s+/)
> > ```
> 
> make a pull request with this and i can merge if you want

Okay
