### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by CheapWave** [whoisbaby/TwitchFollowers#2]
if u do /tfollow (name) (number) the error "TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]" anyone got a fix for that?

**Comment by whoisbaby** [comment]
you need nodejs v12 and good tokens

**Comment by whoisbaby** [comment]
and you need tokens like h59fk2ph9if8jmto2nk2h431sqhpvo
