### ISSUE TITLE
the bot only sends once and then no more folloerts

### ISSUE THREAD

**Issue by raticilo** [whoisbaby/TwitchFollowers#6]
the bot only send followers once and no more!

**Comment by Rayy777** [comment]
It probably crashed, i got 4500 tokens but it doesnt seem to be doing anything

**Comment by raticilo** [comment]
yes

**Comment by abways** [comment]
> It probably crashed, i got 4500 tokens but it doesnt seem to be doing anything

can you give me some tokens if thats possiblie if you can my discord user is Ang's fav <3🌼#0001

**Comment by whoisbaby** [comment]
Host on repl.it is crashing bot
