### ISSUE TITLE
when using tokens as a variable it dosent work

### ISSUE THREAD

**Issue by KCtheDev** [whoisbaby/TwitchFollowers#9]
for example when I do 

"OAuth [inserttokenhere]" it works
but if I do 
var tokens = fs.readFileSync('./TwitchTokens.txt', 'utf-8');
"Oauth ${tokens}"
it says the token is invalid. anyone have a solution?

**Comment by KCtheDev** [comment]
update: im getting the error 'ERR_INVALID_CHAR' but the tokens are correct so why?

**Comment by whoisbaby** [comment]
probably a fs module error reading tokens.txt file
